- name: variables
  hosts: localhost
  vars: 
    Trainer: "sandeep"
    course: "terraform"
    duration: "6months"
  tasks:
  - name: paste
    vars: # Task level variables
      course: "DevOps"
    ansible.builtin.debug:
      msg: "hi we are training {{course}} ,with trainer {{Trainer}} ,duration is {{duration}}"
  
  
  - name: variable paste
    ansible.builtin.debug:
      msg: "hi we are training {{course}} ,with trainer {{Trainer}} ,duration is {{duration}}"









