- name: demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}} "
    loop:
    - linux
    - shell
    - ansible





- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.dnf:
      name: "{{item}}"
   loop:
   - mysql
   - nginx
   - ansible