

- name: install and nginx
  hosts: localhost
  become: yes  # equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: install git 
    ansible.builtin.dnf:
      name: git
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes












